apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: 100150221311.dkr.ecr.ap-south-1.amazonaws.com/jkpedia-repo:latest
        ports:
        - containerPort: 5000
